### ISSUE TITLE
Cannot add solution from knowledge base 

### ISSUE THREAD

**Issue by wawax** [TECLIB/talk#20]
when the plugin is active, when I look for an KB article to include it as a solution it's not working.
When user is redirected back to the ticket form, the solution form is not displayed, and not filled with the KB article description

**Comment by DeschodtV** [comment]
Same problem here, glpi version 0.84.8, talk version 0.84-1.1
It's seems that talk module reset the solution form when user is redirect back to the ticket.
Does anybody find an answer to this bug ?

**Comment by DeschodtV** [comment]
Hi,
You fix the Master Branch, could you do the same on the 0.84 one ?
Thanks in advance,
