### ISSUE TITLE
0.85 beta2: chargement toujours en cours 

### ISSUE THREAD

**Issue by Sismic** [TECLIB/talk#31]
Le plugin est bien activé mais la page reste en chargement

![capture](https://cloud.githubusercontent.com/assets/6815687/6018954/9cbde7a4-ab9b-11e4-8813-ca7fa68c4bc4.JPG)

verdsion utilisé:
PHP 5.4.33-2
GLPI 0.85.2
Apache/2.2.22

**Comment by Sismic** [comment]
vu dans /var/log/apache2/error.log:

[Tue Feb 03 12:00:23 2015] [error] [client] File does not exist: /var/www/glpi/0.85-git, referer: http://serverglpi/glpi-dev/front/ticket.form.php?id=4137

**Comment by orthagh** [comment]
quel boulet je fait...
