### ISSUE TITLE
Private followups and tasks are not hidden

### ISSUE THREAD

**Issue by yannick-photobox** [TECLIB/talk#33]
Hi,

The private tasks and followups are readable by everyone.
I have tried different settings in the profiles but I was not able to hide them. I have tried with both interfaces Standard and Simplified.
Under GLPI tabs (followups and tasks), I can see only the public ones, but everything is shown in 'Processing ticke'.

GLPI 0.85.2
Talk 0.85-1.1

Kind Regards,

**Comment by orthagh** [comment]
Hi.

Thx for this report.

Can you test the fix in this archive : https://github.com/TECLIB/talk/archive/0.85/work.zip

Regards

**Comment by yannick-photobox** [comment]
Hi,

Thanks for the quick reply.
I have just tried. Unfortunately, it is still the same, private messages are viewable by every one.

Regards,

**Comment by orthagh** [comment]
Hi.

Excuse me, i give you a bad link.
Can you test with this one : https://github.com/TECLIB/talk/archive/master.zip

Regards

**Comment by yannick-photobox** [comment]
Hi,

Much better. ;-)
It works perfectly, thank you.

Regards

**Comment by orthagh** [comment]
Great !
